### ISSUE TITLE
"Failed to get the environment" error on Android when using C API

### ISSUE THREAD

**Issue by zhuowei** [kamcord/kamcord-android-sdk#3]
When calling Kamcord_EndDraw, I receive the error

```
I/klog    (23483): Failed to get the environment.
```
and then the application segfaults on a null pointer.

I think this happens because the rendering of the application is done on a separate thread that does not have a Java thread attached (it was created on the native side as a plain PThread), thus GetEnv fails. Perhaps the SDK can detect this and call AttachCurrentThread/DetachCurrentThread instead if this happens?

**Comment by drknotter** [comment]
@zhuowei: A fix for this issue will be going into our next release. Stay tuned!
