### ISSUE TITLE
Any plans for Lenovo support? 

### ISSUE THREAD

**Issue by mynkow** [kamcord/kamcord-android-sdk#6]
Hi,  I  just bought a tablet for my 2yo son to play my talking Tom but the game cannot be installed because kamcord does not support Lenovo devices.  What is the reason for this?  Any plans to make it available any time soon?

**Comment by drknotter** [comment]
@mynkow: We are constantly adding support for more devices as we get access to them for testing. We're making a big push in the next few months to add support for many more devices, so keep your eyes peeled for My Talking Tom/Kamcord updates.
